branches:
  only:
    - devel

# Build worker image (VM template)
image: Visual Studio 2015

# clone directory
clone_folder: c:\projects\vcglib
# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# scripts to run before build
before_build:
  ps: cd apps/tridecimator


# to run your custom scripts instead of automatic MSBuild
build_script:
  ps: qmake
  ps: msbuild